AWSTemplateFormatVersion: 2010-09-09
Description: AWS CloudFormation template to create target group and load balancer

Parameters:
  MyVPC:
    Type: "AWS::EC2::VPC::Id"
    Description: The ID of the VPC
    Default: vpc-024db11d35826730f
  AppInstanceSecurityGroup:
    Type: "AWS::EC2::SecurityGroup::Id"
    Description: The ID of the security group for the application instances
    Default: sg-0615a7367343f78b1
  PublicSubnet1:
    Type: "AWS::EC2::Subnet::Id"
    Description: The ID of the first public subnet
    Default: subnet-01d5bc2cf2c723261
  PublicSubnet2:
    Type: "AWS::EC2::Subnet::Id"
    Description: The ID of the second public subnet
    Default: subnet-07f8d44eb1f769894

Resources:
  MyTargetGroup:
    Type: "AWS::ElasticLoadBalancingV2::TargetGroup"
    Properties:
      Name: myWPTargetGroup
      Protocol: HTTP
      Port: 80
      VpcId: !Ref MyVPC
      HealthCheckProtocol: HTTP
      HealthCheckPath: /wp-login.php
      HealthCheckPort: traffic-port
      HealthCheckIntervalSeconds: 60
      HealthCheckTimeoutSeconds: 50
      HealthyThresholdCount: 2
      UnhealthyThresholdCount: 10
      Matcher:
        HttpCode: 200

  MyLoadBalancer:
    Type: "AWS::ElasticLoadBalancingV2::LoadBalancer"
    Properties:
      Name: myWPAppALB
      Type: application
      Scheme: internet-facing
      IpAddressType: ipv4
      SecurityGroups:
        - !Ref AppInstanceSecurityGroup
      Subnets:
        - !Ref PublicSubnet1
        - !Ref PublicSubnet2

  MyListener:
    Type: "AWS::ElasticLoadBalancingV2::Listener"
    Properties:
      LoadBalancerArn: !Ref MyLoadBalancer
      Protocol: HTTP
      Port: 80
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref MyTargetGroup
